#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ChipManager.Resource", IsApplication=true)]

namespace ChipManager
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int boy = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int boyElim = 2130837506;
			
			// aapt resource value: 0x7F020000
			public const int Button1 = 2130837504;
			
			// aapt resource value: 0x7F020003
			public const int girl = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int girlElim = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int rounded_corner = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int tableBack = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030005
			public const int big = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int clean = 2130903046;
			
			// aapt resource value: 0x7F030000
			public const int ConGame = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ETmoney = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ETname = 2130903042;
			
			// aapt resource value: 0x7F030007
			public const int exit = 2130903047;
			
			// aapt resource value: 0x7F030003
			public const int Gsb = 2130903043;
			
			// aapt resource value: 0x7F030008
			public const int iv1 = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int ll1 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int ll2 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int lstw = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int lv = 2130903052;
			
			// aapt resource value: 0x7F030004
			public const int Msb = 2130903044;
			
			// aapt resource value: 0x7F03000D
			public const int newBet = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int newGame = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int options = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int play = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int pname = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int profile = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int quit = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int radio_All = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int radio_Bet = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int radio_check = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int radio_female = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int radio_male = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int resume = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int s = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int save = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int small = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int sna = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int sns = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int t = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int textView1 = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int tv1 = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int tv2 = 2130903074;
			
			// aapt resource value: 0x7F030023
			public const int tv3 = 2130903075;
			
			// aapt resource value: 0x7F030024
			public const int win = 2130903076;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int game = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int options = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int playerView = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int profile = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int startGame = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int turn = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int winner = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F050000
			public const int GameMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int ic_launcher = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_launcher_foreground = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_launcher_round = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F070000
			public const int pokerMusic2MP3 = 2131165184;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
